/*
 *  arch/mips/sys/sysmacros.h
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2026 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _SYSMACROS_DEV_T
#define _SYSMACROS_DEV_T
  #define major(__device)           ((int)(((__device) >> 8) & 0xFF))
  #define minor(__device)           ((int)((__device) & 0xff))
  #define makedev(__major,__minor)  ((dev_t)(((__major) << 8) | (__minor)))
#endif
