/*
 * This file automatically generated by CONV.EXE
 */
#include <stdio.h>
#include <windows.h>
#include "dllthunk.h"

void DLLLoadFail( char *str )
{
    MessageBox( NULL, "DLL Load Failed", str, MB_OK );
}
